"""empty message

Revision ID: 25b231e51d15
Revises: 
Create Date: 2018-06-29 22:49:38.143338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b231e51d15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_report',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('renewables_ratio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('weather_forecast',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_forecast')
    op.drop_table('generation_report')
    # ### end Alembic commands ###
