"""empty message

Revision ID: 4f0929af3b47
Revises: 25b231e51d15
Create Date: 2018-07-01 21:43:13.111653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0929af3b47'
down_revision = '25b231e51d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_prediction',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('renewables_ratio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_prediction')
    # ### end Alembic commands ###
