"""empty message

Revision ID: 6776f357a4e9
Revises: c5bd0a1c7cf2
Create Date: 2018-06-15 21:11:54.009164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6776f357a4e9'
down_revision = 'c5bd0a1c7cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_forecast', sa.Column('city', sa.String(), nullable=False))
    op.drop_column('weather_forecast', 'city_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_forecast', sa.Column('city_name', sa.VARCHAR(), nullable=False))
    op.drop_column('weather_forecast', 'city')
    # ### end Alembic commands ###
