"""empty message

Revision ID: c5bd0a1c7cf2
Revises: 772f3a38c932
Create Date: 2018-06-07 21:56:51.389706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bd0a1c7cf2'
down_revision = '772f3a38c932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecast',
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('city_name', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_forecast')
    # ### end Alembic commands ###
